apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: argo-cd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 5.40.*
configurations:
- ./kustomizeconfig/clusterwide-resources-suffix.yaml